-- MOMENTUM 15 CLOUD — SUPABASE DATABASE SETUP
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create table if not exists public.momentum_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  device_id text
);

create table if not exists public.momentum_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  updated_at timestamptz not null default now()
);

create table if not exists public.momentum_notification_jobs (
  user_id uuid not null references auth.users(id) on delete cascade,
  id text not null,
  title text not null,
  body text not null default '',
  fire_at timestamptz not null,
  kind text not null default 'reminder',
  url text not null default './',
  sent boolean not null default false,
  sent_at timestamptz,
  source_updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

alter table public.momentum_saves enable row level security;
alter table public.momentum_push_subscriptions enable row level security;
alter table public.momentum_notification_jobs enable row level security;

drop policy if exists "momentum saves select own" on public.momentum_saves;
drop policy if exists "momentum saves insert own" on public.momentum_saves;
drop policy if exists "momentum saves update own" on public.momentum_saves;
drop policy if exists "momentum saves delete own" on public.momentum_saves;
create policy "momentum saves select own" on public.momentum_saves for select to authenticated using (auth.uid() = user_id);
create policy "momentum saves insert own" on public.momentum_saves for insert to authenticated with check (auth.uid() = user_id);
create policy "momentum saves update own" on public.momentum_saves for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "momentum saves delete own" on public.momentum_saves for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "momentum subs select own" on public.momentum_push_subscriptions;
drop policy if exists "momentum subs insert own" on public.momentum_push_subscriptions;
drop policy if exists "momentum subs update own" on public.momentum_push_subscriptions;
drop policy if exists "momentum subs delete own" on public.momentum_push_subscriptions;
create policy "momentum subs select own" on public.momentum_push_subscriptions for select to authenticated using (auth.uid() = user_id);
create policy "momentum subs insert own" on public.momentum_push_subscriptions for insert to authenticated with check (auth.uid() = user_id);
create policy "momentum subs update own" on public.momentum_push_subscriptions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "momentum subs delete own" on public.momentum_push_subscriptions for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "momentum jobs select own" on public.momentum_notification_jobs;
drop policy if exists "momentum jobs insert own" on public.momentum_notification_jobs;
drop policy if exists "momentum jobs update own" on public.momentum_notification_jobs;
drop policy if exists "momentum jobs delete own" on public.momentum_notification_jobs;
create policy "momentum jobs select own" on public.momentum_notification_jobs for select to authenticated using (auth.uid() = user_id);
create policy "momentum jobs insert own" on public.momentum_notification_jobs for insert to authenticated with check (auth.uid() = user_id);
create policy "momentum jobs update own" on public.momentum_notification_jobs for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "momentum jobs delete own" on public.momentum_notification_jobs for delete to authenticated using (auth.uid() = user_id);

grant select, insert, update, delete on public.momentum_saves to authenticated;
grant select, insert, update, delete on public.momentum_push_subscriptions to authenticated;
grant select, insert, update, delete on public.momentum_notification_jobs to authenticated;
grant usage, select on sequence public.momentum_push_subscriptions_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'momentum_saves'
  ) then
    alter publication supabase_realtime add table public.momentum_saves;
  end if;
end $$;
